"""Alter telephone type

Revision ID: 0002
Revises: 0001
Create Date: 2022-04-28 19:31:05.287038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('telephone',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('telephone',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
