"""Alter delivery table

Revision ID: 0008
Revises: 0007
Create Date: 2022-05-16 13:42:33.199653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_deliveryboy',
    sa.Column('deliveryboy_id', sa.Integer(), nullable=True),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deliveryboy_id'], ['delivery_boy.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_deliveryboy')
    # ### end Alembic commands ###
